### ISSUE TITLE
N3dr fails if no config file is provided

### ISSUE THREAD

**Issue by jorianvo** [030/n3dr#100]
**What happened**:
I installed `n3dr` on my Jenkins slave to create a weekly backup of my nexus instance. I added the nexus password to my Jenkins credentials store. The invocation failed is `n3dr` complained about not finding the `~/.n3dr.yaml` file.

**What you expected to happen**:
Jenkins to be able to successfully create a backup of nexus.

**How to reproduce it (as minimally and precisely as possible)**:
Don't create the `~/.n3dr.yaml` but specify the credentials on the command line only.

**Anything else we need to know?**:

**Environment**:
- n3dr version (use `n3dr -v`): 3.3.2

**Comment by 030** [comment]
[![GolangCI](https://golangci.com/badges/github.com/golangci/golangci-lint.svg)](https://golangci.com)

**Comment by 030** [comment]
3.3.3
