### ISSUE TITLE
n3dr fails to deal with nexus 3 servers with self-signed certificates

### ISSUE THREAD

**Issue by titou10titou10** [030/n3dr#107]
**What happened**:
n3dr fails to deal with nexus 3 servers in https with self signed certificates. As an example, retrieve the list of repositories:

    ./n3dr-linux repositories -u xxxx -p xxxx-n https://xxxx -a
    WARN[0000] ~/.n3dr.yaml does not exist or yaml is invalid
    FATA[0000] Get https://xxxx/service/rest/v1/repositories: x509: certificate signed by unknown authority

**What you expected to happen**:
get the list of repositories

**How to reproduce it (as minimally and precisely as possible)**:
use n3dr with a nexus3 repositories with https and a self signed certificate

**Anything else we need to know?**:

**Environment**:
- n3dr version (use `n3dr -v`): 3.3.3
- OS (e.g: `cat /etc/os-release`): RHEL 7.7
- Kernel (e.g. `uname -a`): Linux xxxx 3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by 030** [comment]
Thanks for reporting this.

**Comment by titou10titou10** [comment]
Certificate validation can now be bypassed
A more secure way would be to configure n3dr with the CA certificate of the nexus3 server. This is addresses in #111
