### ISSUE TITLE
Allow n3dr to use the CA certificate of the nexus3 server

### ISSUE THREAD

**Issue by titou10titou10** [030/n3dr#111]
**What would you like to be added**:
Now that n3dr can bypass the nexus3 server certificate validation with the`--insecureSkipVerify`flag (Issue #107), it should be possible to tell n3dr what certificate authority certificate to use when accessing the nexus3 server

**Why is this needed**:
Access nexus3 servers in a secure way instead of bypassing the certificate validation

**Comment by 030** [comment]
* create a self signed cert
* load it in nexus
* load the cert in the golang code

**Comment by 030** [comment]
6.0.9
