### ISSUE TITLE
Not able to push repo data to destination Nexus repo after download

### ISSUE THREAD

**Issue by faheemjmi** [030/n3dr#113]
Not able to push repo data to destination Nexus repo after download

Downloaded content should push to new Nexus repo

Run upload command to reproce
```
n3dr-linux upload -d -u admin -n http://nexus.testserver.com -r Dev_NEW
```
I am able to download but can't upload.getting below error while upload
```
"FATA[0000]/home/travis/gopath/src/github.com/030/n3dr/cmd/upload.go:42 n3dr/cmd.glob..func6() lstat : no such file or directory"
```

**Environment**: Linux
- n3dr version (use `n3dr -v`): 3.3.3
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.4 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by 030** [comment]
Could you indicate whether `"FATA[0000]/home/travis/gopath/src/github.com/030/n3dr/cmd/upload.go:42 n3dr/cmd.glob..func6() lstat : no such file or directory"` is the complete log? If not, could you add some more logging?

**Comment by faheemjmi** [comment]
When running the upload command with flag "-d" I am only getting above mentioned log.

**Comment by 030** [comment]
@faheemjmi Thanks for reporting this. I hope to work on this upcoming weekend.

**Comment by faheemjmi** [comment]
Thanks! It would be really great if we could make it work early next week as I need to do some urgent 
 bulk artifact migration.

**Comment by 030** [comment]
@faheemjmi I created an empty `Dev_NEW` and ran the command:

```
mkdir Dev_NEW
user@host:~/dev/n3dr$ go run main.go upload -d -u admin -n http://nexus.testserver.com -r Dev_NEW
FATA[0000]/home/user/dev/n3dr/cmd/upload.go:42 n3dr/cmd.glob..func6() lstat : no such file or directory            
exit status 1
```

**Comment by 030** [comment]
@faheemjmi Could you use 3.3.5-rc1. The logging has been improved.

**Comment by 030** [comment]
@faheemjmi Did this solve the issue?

**Comment by faheemjmi** [comment]
Sorry for late reply.

Still can't upload ..getting below error 
 
" FATA[0000] no folders with .pom files detected. Please check whether the 'DevNEW' directory contains .pom files "
 
Message seems correct as there's no POM, mostly data is in zip format. But it should also upload.

**Comment by 030** [comment]
Could you share the structure of the folder? Does it only contain zip files? How did you initially store these files? Were these uploaded manually, gradle, maven or something else? Could you issue a `tree` in the download folder?

**Comment by 030** [comment]
@faheemjmi It seems that a pom file is also required to upload a zip file as without it the following error is returned:

```
FATA[0000] HTTPStatusCode: '400'; ResponseMessage: '[{"id":"groupId","message":"Missing required component field 'Group ID'"},{"id":"artifactId","message":"Missing required component field 'Artifact ID'"},{"id":"version","message":"Missing required component field 'Version'"}]'; ErrorMessage: '<nil>' 
exit status 1
```

**Comment by 030** [comment]
Another upload test of a zip without pom:
```
Started Sonatype Nexus OSS 3.21.1-01
Testing upload zips...
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() maven-releases/file1/file1/1.0.0/file1-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() maven-releases/file10/file10/1.0.0/file10-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() maven-releases/file2/file2/1.0.0/file2-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() maven-releases/file3/file3/1.0.0/file3-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() maven-releases/file4/file4/1.0.0/file4-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() maven-releases/file5/file5/1.0.0/file5-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() maven-releases/file6/file6/1.0.0/file6-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() maven-releases/file7/file7/1.0.0/file7-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() maven-releases/file8/file8/1.0.0/file8-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() maven-releases/file9/file9/1.0.0/file9-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() ZIP found maven-releases/file1/file1/1.0.0/file1-1.0.0.zip 
DEBU[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:277 github.com/sirupsen/logrus.(*Entry).Debug() URL                                           multipart="maven2.asset9=@maven-releases/file1/file1/1.0.0/file1-1.0.0.zip,maven2.asset9.extension=zip" url="http://localhost:9999/service/rest/v1/components?repository=maven-releases"
FATA[0000]/home/ben/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() HTTPStatusCode: '400'; ResponseMessage: '[{"id":"groupId","message":"Missing required component field 'Group ID'"},{"id":"artifactId","message":"Missing required component field 'Artifact ID'"},{"id":"version","message":"Missing required component field 'Version'"}]'; ErrorMessage: '<nil>'
```

**Comment by 030** [comment]
The same issue occurs if nexus 3.9.0 is used:

```
Started Sonatype Nexus OSS 3.9.0-01
Testing upload...
FATA[0000] HTTPStatusCode: '400'; ResponseMessage: '[{"id":"groupId","message":"Missing required component field 'Group ID'"},{"id":"artifactId","message":"Missing required component field 'Artifact ID'"},{"id":"version","message":"Missing required component field 'Version'"}]'; ErrorMessage: '<nil>'
```

**Comment by 030** [comment]
However, if a pom would exist then the upload of zips will be omitted currently. I will add a commit to ensure that publication of zips will occur if poms exist.

**Comment by 030** [comment]
3.4.0 is able to upload zip files if pom files exist

**Comment by faheemjmi** [comment]
We are using the latest Nexus version i.e. 3.21.1 . However above logs are from 3.16 where I am doing this testing. There's huge numbers of team uploading their artifacts. Some use maven,gradle and some simply use curl , mvn upload to upload the artifacts.

If possible could you make this utility to download components based on some group ids instead of all the repo data. For example I want to download data under "com.test" only ?

**Comment by 030** [comment]
@faheemjmi  yes that should be possible. I will have a look the upcoming weekend and let you know when it is implemented.

**Comment by faheemjmi** [comment]
Thanks in advance @030  ! It would be really a great help for me.

**Comment by 030** [comment]
@faheemjmi Could you try 3.5.0? The documentation has been updated as well. It is possible to use a regex from now on:

```
-x 'some/repo42'
```

**Comment by faheemjmi** [comment]
It's not working on Nexus 3.21.1-01 version. Got below error

FATA[0000] ResponseCode: '404' and Message '404 Not Found' for URL: http://10.20.30.40:8081//service/rest/v1/assets?repository=maven-releases

However it worked on a test version of Nexus 3.16.1-02.  But my Production is on 3.21.1-01,

**Comment by 030** [comment]
I just tested with the latest nexus and the integration test works as well. Based on the provided error message, it seems that the repository 'maven-releases' does not exist in your production server. Could you try the `repositories` sub command or specify a repository that exists in your production.

Option 1

```
n3dr backup -n http://localhost:9999 -u admin -r <repository-name-that-exists-in-nexus3>
```

Option 2

```
n3dr repositories -n http://localhost:9999 -u admin -b -x 'some/group42'
```

**Comment by faheemjmi** [comment]
I got the exact issue. When there's no pom it's not downloading any data. I uploaded a zip file and checked generate pom then it worked. There are groups which have only zip no pom. How could I download those group data ?

**Comment by faheemjmi** [comment]
One more clarification. On my Production in the repo from where I am going to download data is having total data around 1 TB. Is this script going to search entire data and then download that particular group?

**Comment by 030** [comment]
> I got the exact issue. When there's no pom it's not downloading any data. I uploaded a zip file and checked generate pom then it worked. There are groups which have only zip no pom. How could I download those group data ?

Could you indicate how many ZIP files you have without pom? I wonder how these zip files were uploaded back in the day. If one uses the upload option in Nexus then the upload will fail if one did not specify a pom file. Perhaps the pom file is in a parent folder, i.e. the pom file is somewhere else in the Nexus server?

> I tested this on a test instance with localhost. But when I am trying on production which is hosted in AWS with HTTPS this this command does nothing.

Could you indicate whether the production server has a self-signed certificate? If true, then there is an option to load a custom CA.

> One more clarification. On my Production in the repo from where I am going to download data is having total data around 1 TB. Is this script going to search entire data and then download that particular group?

Yes it will check all URLs and only download the files if the regex matches a URL.

> Is it possible to pass multiple group ids in single command so that we don't need to search entire repo everytime we download data ?

Do you have some examples regarding the group ids? It is possible to use a regex so it should be possible to run it once.

**Comment by rluvaton** [comment]
This error still persists, I trying to download apt registry and upload it and it throws an error 
says `no folders with .pom files detected ...`.

**Comment by 030** [comment]
@rluvaton what version of n3dr do you use? How does the structure of your folder look like? .pom's are required for uploading the files. Did you download the artifacts from another repository using n3dr?

**Comment by rluvaton** [comment]
> @rluvaton what version of n3dr do you use?

3.6.3

> How does the structure of your folder look like? .pom's are required for uploading the files.

```
download:
  - apt-ubuntu20.04:
    - dists:
      - ...
    - pools:
      - ...
```
> Did you download the artifacts from another repository using n3dr?

**Comment by 030** [comment]
@rluvaton Could you indicate whether the repository is a non-maven one? E.g. it is an ubuntu repository as apt-ubuntu20.04 is specified? If true, could you create a new issue as currently only maven upload is supported? We have to write a test that is able to upload apt content to an apt repository. Probably n3cac has to be used to automate the creation of the apt repository, download and subsequently upload the content.

**Comment by rluvaton** [comment]
> @rluvaton Could you indicate whether the repository is a non-maven one? E.g. it is an ubuntu repository as apt-ubuntu20.04 is specified? If true, could you create a new issue as currently only maven upload is supported? We have to write a test that is able to upload apt content to an apt repository. Probably n3cac has to be used to automate the creation of the apt repository, download and subsequently upload the content.

Done #140

**Comment by 030** [comment]
@faheemjmi I will try to upload a zip without pom to a raw repository nexus type

**Comment by 030** [comment]
@faheemjmi Could you try to upload the zip using n3dr 5.1.1? If it false, please reopen the issue.
