### ISSUE TITLE
Store downloaded artifacts in OCI Object Storage

### ISSUE THREAD

**Issue by vsoloviov** [030/n3dr#122]
**What would you like to be added**: I would like to store exported Nexus artifacts in [OCI Object Storage](https://www.oracle.com/cloud/storage/object-storage.html)

**Why is this needed**:
Object Storage is a durable storage, you don't need to care about space management and availability.
It can be integrated with other services which may need builds archives (e.g. if you don't want to keep all of them on Nexus)

**Comment by 030** [comment]
Thank you for creating a PR. I hope to review it this week.

**Comment by 030** [comment]
3.6.0
