### ISSUE TITLE
brew

### ISSUE THREAD

**Issue by 030** [030/n3dr#123]
**What would you like to be added**:

brew package

**Why is this needed**:

To ensure that n3dr could be installed on MacOSX using brew

**Comment by laurentenhoor** [comment]
I will have a look

**Comment by 030** [comment]
https://docs.brew.sh/Formula-Cookbook

**Comment by 030** [comment]
https://github.com/Homebrew/homebrew-core/pull/73638

**Comment by 030** [comment]
```
==> FAILED
==> Installing 'bundler' gem
n3dr:
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 1 problem in 1 formula detected

==> brew bottle --verbose --json n3dr
```
