### ISSUE TITLE
Retry failed requests and do not exit when a single artifact download failed

### ISSUE THREAD

**Issue by vsoloviov** [030/n3dr#134]
First of all, n3dr is AWESOME!

**What would you like to be added**:

- Retry failed requests
- Log a failed download and proceed to the next one.

**Why is this needed**:

On systems with a huge number of artifacts it takes a while to download everything and it's confusing when the whole process ended up because of a short network issue or in cases when artifact data is corrupted.

**Examples**:
```
# docker logs a5e206740344
time="2020-07-10T11:08:32Z" level=info msg="HomeDir: '/home/jenkins'"
time="2020-07-10T16:30:11Z" level=info msg="Assembling downloadURLs 'releases'"
 64656 / 74888 time="2020-07-10T21:06:13Z" level=fatal msg="Get \"https://nexus/service/rest/v1/assets?repository=releases&continuationToken=55258bea3c6fae8a1c9b8bc8d0c74cdc\": EOF"
 64735 / 74888   86.44% 43m17
```

That's sad when after 10 hours collecting URLs the process failed with EOF.

Or 
```
time="2020-07-12T08:46:39Z" level=fatal msg="URL: 'https://nexus/repository/releases/archetype-catalog.xml' does not seem to contain an artifactName"
```

This file could be uploaded by mistake, I don't remember, but that's not a reason to stop the backup process.

Or sometimes it happens: data file has been damaged on a filesystem or removed, so the backup process should not be interrupted, e.g.

```
 12 / 4442 [>------------------------------------------------------------------------------------------------------------------------------------------]   0.27% 01m01s
FATA[0279] ResponseCode: '500' and Message '500 javax.servlet.ServletException: org.sonatype.nexus.repository.storage.RetryDeniedException: Exceeded retry limit' for URL: https://nexus-dev/repository/thirdparty/com/oracle/oim/wlthint3client/10.3.6.0/wlthint3client-10.3.6.0.pom 
```

Thank you!

**Comment by jdonkervliet** [comment]
This has not been completely fixed. I received the error `FATA[0076] URL: 'https://<url>/nexus/repository/<repo-name>/archetype-catalog.xml' does not seem to contain an artifactName` in version 5.2.1.

**Comment by 030** [comment]
This is interesting. Could you share a sample file. Currently the integration tests assume that maven-metadata.xml files exist. I googled a little bit and found https://maven.apache.org/archetype/maven-archetype-plugin/specification/archetype-catalog.html Is this applicable?

**Comment by jdonkervliet** [comment]
I'm running

```
./n3dr-osx backup \
    --anonymous \
    --directory-prefix <artifact-dir> \
    -n https://<nexus-domain>/nexus \
    -r <repo-name>
```

and my remote repository contains artifact directories and these files:

- archetype-catalog.xml
- archetype-catalog.xml.md5
- archetype-catalog.xml.sha1

I did not upload these files to the repository on purpose.

**Comment by jdonkervliet** [comment]
I'm guessing artifact names are not allowed to contain a period (.). Would it make sense to simply ignore all strings containing a period?

**Comment by 030** [comment]
```
+++++++++++++++++panic: send on closed channel

goroutine 282 [running]:
n3dr/cli.Nexus3.continuationTokenRecursionChannel.func1(0xa58b11, 0x2, 0xc0005d01e0, 0x7ffe9cfbbdb9, 0x18, 0xc000260460, 0x3, 0xc000260480, 0xc, 0xc00047c110, ...)
        /root/parts/n3dr/build/cli/backup.go:264 +0x4c7
created by n3dr/cli.Nexus3.continuationTokenRecursionChannel
        /root/parts/n3dr/build/cli/backup.go:249 +0x3c8
```

**Comment by 030** [comment]
@jdonkervliet Could you try 3.5.2? It will probably fail, but the logging has been improved and it will help solving the issue. Probably the `archetype-catalog.xml` resides in the main repository rather than in a separate folder.

**Comment by 030** [comment]
5.2.2 contained another issue. 5.2.3 has been released.

**Comment by jdonkervliet** [comment]
Heh, weird stuff happening on my side. This is with 5.2.3:

1.
```
~ ./n3dr-osx --version
Error: unknown flag: --version
```

2.
```
~ ./n3dr-osx backup \
    --anonymous \
    --directory-prefix OUTPUT_DIR \
    -n NEXUS_URL \
    -r REPO
FATA[0001] stat /Users/logo/text-image-com-n3dr.txt: no such file or directory
```

**Comment by 030** [comment]
Hmm this is caused by omission of packr in the CI. I will fix it.

**Comment by 030** [comment]
related #176

**Comment by 030** [comment]
@jdonkervliet  Could you try 5.2.4?

**Comment by jdonkervliet** [comment]
Almost worked!
```
INFO[0000]/Users/travis/gopath/src/github.com/030/n3dr/cli/backup.go:293 github.com/030/n3dr/cli.Nexus3.StoreArtifactsOnDiskChannel() Backing up: '<removed repo name>'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++FATA[0173]/Users/travis/gopath/src/github.com/030/n3dr/cmd/backup.go:42 github.com/030/n3dr/cmd.glob..func1() URL: 'https://<some nexus url>/repository/<group repository>/archetype-catalog.xml' does not seem to contain a Maven artifact
```

**Comment by 030** [comment]
@jdonkervliet what nexus version do you use and how did you upload this file to the repository? I tried to reproduce this by using the upload functionality in Nexus and even when I upload a plain text file the structure looks as follows:

![Uploading image.png…]()

**Comment by 030** [comment]
@jdonkervliet what nexus version do you use and how did you upload this file to the repository? I tried to reproduce this by using the upload functionality in Nexus and even when I upload a plain text file the structure looks as follows:

**Comment by 030** [comment]
@jdonkervliet what nexus version do you use and how did you upload this file to the repository? I tried to reproduce this by using the upload functionality in Nexus and even when I upload a plain text file the structure looks as follows:

![Uploading image.png…]()

**Comment by 030** [comment]
I will adjust the regex from:

```
regexp.MustCompile("^.*?/" + n.Repository + "/(.*)/(.+)$
```

to:

```
regexp.MustCompile("^.*?/" + n.Repository + "/(.*)$
```

**Comment by 030** [comment]
I will adjust the regex from:

```
regexp.MustCompile("^.*?/" + n.Repository + "/(.*)/(.+)$
```

to:

```
regexp.MustCompile("^.*?/" + n.Repository + "/(.*)$
```

**Comment by jdonkervliet** [comment]
I am running Nexus version `OSS 3.26.1-02`.

I do not recall uploading this file myself. It is located in a group repository. I think it may have been automatically generated by Nexus. See: https://stackoverflow.com/questions/22837962/how-to-update-archetype-catalog-in-nexus-repository

**Comment by 030** [comment]
@jdonkervliet Apparently, one could also navigate to https://<nexus_fqdn>/repository/<repository_name>/archetype-catalog.xml, see https://community.sonatype.com/t/deploy-or-make-nxrm3-generate-archetype-catalog-xml/2531 to create a `archetype-catalog.xml`. I will include it in the tests.

**Comment by 030** [comment]
@jdonkervliet Could you try whether 5.2.7 solves the issue?

**Comment by jdonkervliet** [comment]
For completeness: I tested version `6.0.0`, which successfully solves the problem I mentioned in this issue. Thanks, @030!
