### ISSUE TITLE
Upload only works for maven

### ISSUE THREAD

**Issue by rluvaton** [030/n3dr#140]
**What happened**:
I trying to upload my apt registry that I downloaded using this tool and it throws an error says no `.pom` files found

The command I ran:
```bash
n3dr upload -u <user-name> -p <password> -n http://localhost:8081 -r apt-ubuntu20.04 -d
```
The Output
```
INFO[0000] HomeDir: '/home/team'
FATA[0000]/home/travis/gopath/pkg/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() lstat apt-ubuntu20.04: no such file or directory
```

**What you expected to happen**:
Should upload any registry

**How to reproduce it (as minimally and precisely as possible)**:
1. Create **proxy** apt registry
2. Download some apt things
3. Use this to tool to backup the registry
4. Create **hosted** apt registry
5. Try to upload the backup to the **hosted** registry
   `n3dr upload -u <user-name> -p <password> -n http://localhost:8081 -r apt-ubuntu20.04`

**Anything else we need to know?**:

Original issue comment https://github.com/030/n3dr/issues/113#issuecomment-659500587

Folder structure of the backup:

```yaml
download:
  - apt-ubuntu20.04:
    - dists:
      - ...
    - pool:
      - ...
```

**Environment**:
- nexus version: 3.25.0-03
- n3dr version (use `n3dr -v`): 3.6.3
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04 LTS
- Kernel (e.g. `uname -a`): Linux xxxxxx 5.4.0-26-generic #30-Ubuntu SMP <date> x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by rluvaton** [comment]
@030 I think it's a bug (you wrote in the README that this feature supported)

**Comment by 030** [comment]
@rluvaton According to the nexus documentation, multiupload is not possible in conjunction with apt: 


https://help.sonatype.com/repomanager3/user-interface/uploading-components
Repository format | Valid file types | Multiple file upload
-- | -- | --
Apt | .deb, .udeb | No
Maven (release only) | No restrictions, but common types include .pom, .jar, and .zip | Yes



I tried it and it failed:

```
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 java.io.IOException: invalid header ?7zXZ
< Date: Wed, 29 Jul 2020 16:58:49 GMT
< Server: Nexus/3.25.0-03 (OSS)
< X-Content-Type-Options: nosniff
< Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< Pragma: no-cache
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate, post-check=0, pre-check=0
< Expires: 0
< Content-Type: text/html
< Content-Length: 1925
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 1925)
* Closing connection 0```

What we can do instead is supporting the upload of single debians.

**Comment by 030** [comment]
Related: https://github.com/030/n3dr/issues/113

**Comment by rluvaton** [comment]
> What we can do instead is supporting the upload of single debs.

I think we should iterate over the files and upload them one at a time

**Comment by 030** [comment]
@rluvaton The upload of multiple deb files works on my machine. I have to fix the CI and update the README and CHANGELOG. I hope to continue tomorrow evening.

**Comment by 030** [comment]
@rluvaton Could you check whether 5.1.1 solves the issue? If false, please reopen the issue.

**Comment by rluvaton** [comment]
I'll try on Sunday.

Thank you very much for the fix 😀

**Comment by ariel22411** [comment]
@030 In v5.1.1 you haven't exported to linux

**Comment by 030** [comment]
@ariel22411 Something went wrong in the CI. I will have a look.

**Comment by 030** [comment]
@ariel22411 The linux artifacts have been created and published as well by the CI. It was unclear why it failed.

**Comment by rluvaton** [comment]
@030 I can't upload It saying that `./apt-ubuntu20.04/dists: is a directory`
```

rluvaton@DESKTOP-HEFABQ7:/tmp/n3dr/download954218459$ ~/n3dr upload -u admin -p admin -n http://localhost:8081 -r apt-ubuntu20.04 -m=false -d
INFO[0000]/home/travis/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() n3drHomeDir: '/home/rluvaton/.n3dr'
INFO 2020/08/09 12:38:59 Trying to resolve absolute path to /home/rluvaton/.n3dr
INFO 2020/08/09 12:38:59 adding /home/rluvaton/.n3dr to paths to search
DEBU[0000]/home/travis/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() configFile: '/home/rluvaton/.n3dr/config.yml'
INFO 2020/08/09 12:38:59 Attempting to read in config file
INFO 2020/08/09 12:38:59 Searching for config in  [/home/rluvaton/.n3dr]
DEBUG 2020/08/09 12:38:59 Searching for config in  /home/rluvaton/.n3dr
DEBUG 2020/08/09 12:38:59 Checking for /home/rluvaton/.n3dr/config.json
DEBUG 2020/08/09 12:38:59 Checking for /home/rluvaton/.n3dr/config.toml
DEBUG 2020/08/09 12:38:59 Checking for /home/rluvaton/.n3dr/config.yaml
DEBUG 2020/08/09 12:38:59 Checking for /home/rluvaton/.n3dr/config.yml
DEBUG 2020/08/09 12:38:59 Checking for /home/rluvaton/.n3dr/config.properties
DEBUG 2020/08/09 12:38:59 Checking for /home/rluvaton/.n3dr/config.props
DEBUG 2020/08/09 12:38:59 Checking for /home/rluvaton/.n3dr/config.prop
DEBUG 2020/08/09 12:38:59 Checking for /home/rluvaton/.n3dr/config.hcl
WARN[0000]/home/travis/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() Looked for config file: '/home/rluvaton/.n3dr/config.yml', but found: '' including err: 'Config File "config" Not Found in "[/home/rluvaton/.n3dr]"'. Check whether it exists, the YAML is correct and the content is valid
false
INFO[0000]/home/travis/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() Uploading file dists to http://localhost:8081
FATA[0000]/home/travis/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Post "http://localhost:8081/repository/apt-ubuntu20.04/": read ./apt-ubuntu20.04/dists: is a directory

```

**Comment by 030** [comment]
Upload to Maven snapshots and Maven proxy does not work as well:

```
FATA[0000] HTTPStatusCode: '400'; ResponseMessage: '[{"id":"*","message":"Upload to snapshot repositories not supported, use the maven client."}]'; ErrorMessage: '<nil>' 
```

```
FATA[0000] HTTPStatusCode: '400'; ResponseMessage: '[{"id":"*","message":"Uploading components to a 'proxy' type repository is unsupported, must be 'hosted'"}]'; ErrorMessage: '<nil>'
```

The readme has to be updated. The readme should also indicate that only deb files can be uploaded to a apt repository in nexus and backing up a proxy content and subsequently upload it is not supported. @rluvaton you could assemble the deb files, store them in a folder, e.g. folder/1.deb, folder/2.deb. It is important that the depth is max 1 otherwise the upload will fail.
