### ISSUE TITLE
Set a list of repositories to be downloaded

### ISSUE THREAD

**Issue by vsoloviov** [030/n3dr#149]
**What would you like to be added**:
I would like to download a list of repositories, not a single repository and not all of them

**Why is this needed**:
I'd like to execute n3dr once to download all repositories I want, but `n3dr repositories` is not an option, because I don't want to download public mirrors and unsupported repositories.

**Comment by 030** [comment]
@vsoloviov Thank you again. I added you to the CHANGELOG and 5.0.1 has been released. I am now busy implementing channels to speed up the downloads.
