### ISSUE TITLE
n3dr hangs when URL has trailing slash (/)

### ISSUE THREAD

**Issue by jdonkervliet** [030/n3dr#158]
**What happened**:

I tried to create a backup of a repository on my Nexus 3, resulting in n3dr hanging almost immediately and indefinitely.

I ran the following command:
```
~/n3dr-osx backup \
    --anonymous \
    -n <url>/ \
    -r <repo_name>
```

This is the corresponding line from the receiving web server.
```
[31/Aug/2020:09:02:15 +0000] "GET //service/rest/v1/assets?repository=<repo_name> HTTP/1.1" 404 1998 "-" "Go-http-client/1.1" "-"
```

This are the last two lines of STDOUT output from n3dr before hanging.
```
INFO[0000] Processing repository: <repo_name>
Backup:  <repo_name>
```

**What you expected to happen**:

I expect n3dr to exit with an error status code, telling me that retrieving the provided URL results in a 404.
Alternatively, I expect n3dr to automatically trim the trailing `/` and complete the command successfully. 

**How to reproduce it (as minimally and precisely as possible)**:

Run the following code with a valid Nexus 3  <url>, and add a trailing `/` to the URL:
```
~/n3dr-osx backup \
    --anonymous \
    -n <url>/ \
    -r <repo_name>
```

**Anything else we need to know?**:

**Environment**:
- nexus version: 3.26.1-02
- n3dr version: 5.2.0
- OS: MacOS
- Kernel (`uname -rs`): Darwin 18.7.0

**Comment by 030** [comment]
@jdonkervliet Thank you for reporting this. The issue has been resolved in 5.2.1. Please let me know if other issues occur.
