### ISSUE TITLE
Upload of NPM artifacts

### ISSUE THREAD

**Issue by GeorgeGkinis** [030/n3dr#160]
**What would you like to be added**:
I would like to be able to upload **nugget**, **npm** and other repository types

**Why is this needed**:
I am trying to migrate **npm**, **nugget** and other repository types

I have already tried :
```
n3dr-windows.exe` upload --directory-prefix \
"Z:\repo\nexus-migration\repositories" -u n3dr \
-p <pass> -n http://<URL> -r nuget-hosted
```

response :  
```
time="2020-09-22T14:00:57+02:00" level=info 
msg="n3drHomeDir: 'C:\\Users\\<user>\\.n3dr'"
time="2020-09-22T14:00:57+02:00" level=warning
msg="Looked for config
file: 'C:\\Users\\<user>\\.n3dr\\config.yml', but found: 
'' including err: 'Config File \"config\" Not Found
in \"[C:\\\\Users\\\\<user>\\\\.n3dr]\"'. Check whether it exi
sts, the YAML is correct and the content is valid"
false
time="2020-09-22T14:00:57+02:00" level=info
msg="Uploading file KvK.Api.Core.Startup
to http://<URL>"
time="2020-09-22T14:00:57+02:00" level=fatal
msg="Post \"http://<URL>/repository/nuget-hosted/\":
read ./nuget-hosted/KvK.Api.Core.Startup: The handle is invalid."
```

**Comment by GeorgeGkinis** [comment]
Actually i added the -d flag for some debug output : 
```
time="2020-09-22T15:11:48+02:00" level=fatal msg="open nuget-hosted: The system cannot find the file specified." func=n3dr/cmd.glob..func3 file="C:/Users/travis/gopath/src/github.com/030/n3dr/cmd/upload.go:25"
```

If i Look at upload.go:23 i see : 
[err := n.Upload(maven)](https://github.com/030/n3dr/blob/0bdb3eb1823b85353a8963096320b2e1c79bc435/cmd/upload.go#L23)

I specifically added -m=false to the executed command.

It seems that the 'maven bool' is set at true.
This could be a bug.

**Comment by 030** [comment]
@GeorgeGkinis Nuget will be addressed in GH-181. In this issue the focus will be on the uploading of NPM artifacts.

**Comment by 030** [comment]
```
curl -u "admin:${PASSWORD}" -X PUT -v -include -F package=@nuget-hosted/n3dr.5.2.6.nupkg "http://localhost:9999/repository/nuget-hosted/" -f
```

**Comment by 030** [comment]
```
    # curl -u "admin:<pw>" -X POST -v -include \
    # -F package=@REPO_NAME_HOSTED_NPM/babel-core.tgz \
    # http://localhost:9999/service/rest/internal/ui/upload/REPO_NAME_HOSTED_NPM
```

**Comment by 030** [comment]
@GeorgeGkinis Could you try to upload NPM packages using 6.0.0?

**Comment by richardzorge** [comment]
> **What would you like to be added**:
> I would like to be able to upload **nugget**, **npm** and other repository types
> 
> **Why is this needed**:
> I am trying to migrate **npm**, **nugget** and other repository types
> 
> I have already tried :
> 
> ```
> n3dr-windows.exe` upload --directory-prefix \
> "Z:\repo\nexus-migration\repositories" -u n3dr \
> -p <pass> -n http://<URL> -r nuget-hosted
> ```
> 
> response :
> 
> ```
> time="2020-09-22T14:00:57+02:00" level=info 
> msg="n3drHomeDir: 'C:\\Users\\<user>\\.n3dr'"
> time="2020-09-22T14:00:57+02:00" level=warning
> msg="Looked for config
> file: 'C:\\Users\\<user>\\.n3dr\\config.yml', but found: 
> '' including err: 'Config File \"config\" Not Found
> in \"[C:\\\\Users\\\\<user>\\\\.n3dr]\"'. Check whether it exi
> sts, the YAML is correct and the content is valid"
> false
> time="2020-09-22T14:00:57+02:00" level=info
> msg="Uploading file KvK.Api.Core.Startup
> to http://<URL>"
> time="2020-09-22T14:00:57+02:00" level=fatal
> msg="Post \"http://<URL>/repository/nuget-hosted/\":
> read ./nuget-hosted/KvK.Api.Core.Startup: The handle is invalid."
> ```

This error only occurs on windows. Resolve: move all tar files in root repository dir.
