### ISSUE TITLE
possibility of downloading artifacts from a nuget repository

### ISSUE THREAD

**Issue by numb95** [030/n3dr#181]
Hi.
I really interested in this project and really loved it.
I want to use this tool to download and upload NuGet repositories. I want to know when it is possible to have this feature?

thanks.

**Comment by 030** [comment]
```
curl -u "admin:${PASSWORD}" -X PUT -v -include -F package=@nuget-hosted/n3dr.5.2.6.nupkg "http://localhost:9999/repository/nuget-hosted/" -f
```

**Comment by 030** [comment]
@numb95 upload of nuget works since 6.0.0.

**Comment by 030** [comment]
will be implemented in gh-215
