### ISSUE TITLE
zip directory structure

### ISSUE THREAD

**Issue by richardzorge** [030/n3dr#189]
**What would you like to be added**:
Now backup zip has next structure, for example:
backup.zip\download1234567\npm-hosted\@babel\code-frame\code-frame-7.12.11.tgz

Then, will we try upload (on windows), we has error

"bla bla bla: The handle is invalid."

Need put all *.tar in root repository directory, without download directory, for example:
backup.zip\npm-hosted\code-frame-7.12.11.tgz

**Why is this needed**:
If we extract zip archive and run:
 n3dr.exe upload -n http://localhost:8081  -u n3dr -p <pass> -r npm-hosted -t npm -d
we get error.
With new zip structure all worked

Thanks

**Comment by 030** [comment]
I just checkt the library and unfortunately it does not seem to be possible to exclude the top folder.
