### ISSUE TITLE
Ensure that it does not end with a '/'. Error: 'URL: regular expression mismatch' 

### ISSUE THREAD

**Issue by richardzorge** [030/n3dr#190]
**What happened**: 
When i run upload npm packages from backup, i get error
command: ./n3dr upload -n http://192.168.1.139:8081  -u n3dr -p <pass> -r npmhosted -t npm -d
**What you expected to happen**:
upload all npm tar files

**How to reproduce it (as minimally and precisely as possible)**:
download release for linux, run command **./n3dr upload -n http://192.168.1.139:8081  -u <user> -p <pass> -r npmhosted -t npm -d**

**Anything else we need to know?**:
On Windows all work

console output:
@localhost: ./n3dr upload -n http://192.168.1.139:8081  -u <user> -p <pass> -r npmhosted -t npm -d

<logo>

INFO[0000]/home/travis/gopath/src/github.com/030/n3dr/cmd/root.go:62 github.com/030/n3dr/cmd.configFile() n3drHomeDir: '/home/skygtr/.n3dr'            
INFO 2021/01/07 21:24:05 Trying to resolve absolute path to /home/skygtr/.n3dr
INFO 2021/01/07 21:24:05 adding /home/skygtr/.n3dr to paths to search
DEBU[0000]/home/travis/gopath/src/github.com/030/n3dr/cmd/root.go:69 github.com/030/n3dr/cmd.configFile() configFile: '/home/skygtr/.n3dr/config.yml'  
INFO 2021/01/07 21:24:05 Attempting to read in config file
INFO 2021/01/07 21:24:05 Searching for config in  [/home/skygtr/.n3dr]
DEBUG 2021/01/07 21:24:05 Searching for config in  /home/skygtr/.n3dr
DEBUG 2021/01/07 21:24:05 Checking for /home/skygtr/.n3dr/config.json
DEBUG 2021/01/07 21:24:05 Checking for /home/skygtr/.n3dr/config.toml
DEBUG 2021/01/07 21:24:05 Checking for /home/skygtr/.n3dr/config.yaml
DEBUG 2021/01/07 21:24:05 Checking for /home/skygtr/.n3dr/config.yml
DEBUG 2021/01/07 21:24:05 Found:  /home/skygtr/.n3dr/config.yml
DEBUG 2021/01/07 21:24:05 Reading file:  /home/skygtr/.n3dr/config.yml
INFO[0000]/home/travis/gopath/src/github.com/030/n3dr/cmd/root.go:128 github.com/030/n3dr/cmd.parseConfig() Using config file: '/home/skygtr/.n3dr/config.yml' 
FATA[0000]/home/travis/gopath/src/github.com/030/n3dr/cmd/upload.go:21 github.com/030/n3dr/cmd.glob..func3() The Nexus3 URL seems to be incorrect. Ensure that it does not end with a '/'. Error: 'URL: regular expression mismatch'

P.S.: In upload help grammaticaly error
Usage:
  **nd3r** upload [flags]

**Environment**: 
- nexus version: 3.27.0-03
- n3dr version (use `n3dr -v`): 6.0.0
- OS (e.g: `cat /etc/os-release`): Linux  Debian 4.19.152-1 (2020-10-18)
- Kernel (e.g. `uname -a`): 4.19.0-12-amd64
- Others:

**Comment by 030** [comment]
Todo
* add validation of parameters
* `INFO[0000]/home/travis/gopath/src/github.com/030/n3dr/cli/upload.go:134 github.com/030/n3dr/cli.Nexus3.Upload() 0 Upload ''                                  
FATA[0000]/home/travis/gopath/src/github.com/030/n3dr/cmd/upload.go:25 github.com/030/n3dr/cmd.glob..func3() The string should at least contain a '=', but was: ''`
* reproduce this bug

**Comment by richardzorge** [comment]
Привет, сегодня на работе я попробовал загрузить пакеты и обнаружил, что эта ошибка не свзязана с операционной системой. Ошибка возникает когда n3dr.exe запускается на сервере отличном от сервера Sonatype OSS. То есть всё заработало, когда я запустил с флагом       _-r http://localhost_

**Comment by envyj020** [comment]
@030 Any ETA to patch the upload process? Thanks

**Comment by 030** [comment]
@envyj020 Could you try 6.0.1 and let me know if the issue has been resolved?

**Comment by envyj020** [comment]
@030 6.0.1 can't be build, `main.go` as well as other project directories present at 6.0.0 were somehow removed.

**Comment by 030** [comment]
It does not have to built as the binaries reside in releases section, see https://github.com/030/n3dr/tree/6.0.1 If you would like to build the app then you could build it from the cmd/n3dr directory.

**Comment by envyj020** [comment]
@030 now the upload process for maven is working again, thank you for following up!
