### ISSUE TITLE
Version 6.0.1 not available on https://chocolatey.org/

### ISSUE THREAD

**Issue by gfinesch** [030/n3dr#195]
Good Morning, 

**What happened**:
I run command 
`choco install n3dr`

**What you expected to happen**:
Download and install version 6.0.1 but I get version 6.0.0

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
If I execute upload command with version 6.0.0 I get the message

level=fatal msg="The string should at least contain a '=', but was: ''" func=github.com/030/n3dr/cmd.glob..func3 file="C:/Users/travis/gopath/src/github.com/030/n3dr/cmd/upload.go:25"

I know it's a bug solved a couple of weeks ago on version 6.0.1 but I can only download version 6.0.0 because version 6.0.1 is not available yet on Chocolatey

**Environment**:
Windows 10
Nexus3
n3dr 6.0.0

**Comment by 030** [comment]
@gfinesch I just created a ticket https://github.com/digitalcoyote/chocolatey-packages/issues/15 where the chocolatey package is maintained.

**Comment by 030** [comment]
@gfinesch  6.0.1 is available at chocolatey

**Comment by gfinesch** [comment]
Thank you for your support!
