### ISSUE TITLE
Cannot upload a downloaded folder containing only a POM file.

### ISSUE THREAD

**Issue by kubealex** [030/n3dr#202]
**What happened**:

Cannot upload downloaded elements (with n3dr backup) when donwloaded folder only contains POM 

DEBU[0016]/home/runner/work/n3dr/n3dr/internal/artifacts/upload.go:260 github.com/030/n3dr/internal/artifacts.(*Nexus3).readMavenFilesAndUpload() 39 Detecting artifacts in folder XXX/1.0.10-RC1'
WARN[0016]/home/runner/work/n3dr/n3dr/internal/artifacts/upload.go:81 github.com/030/n3dr/internal/artifacts.artifactTypeDetector() 'XXX/1.0.10-RC1/adapter-event-enrichment-1.0.10-RC1.pom' not an artifact
FATA[0016]/home/runner/work/n3dr/n3dr/cmd/n3dr/upload.go:23 main.glob..func3() The sb.String() should not be empty. Verify whether the path: 'XXX/1.0.10-RC1' contains artifacts

[xxx@localhost ~]# ls -ltra XXX/1.0.10-RC1 
-rw-r--r--. 1 root root 4239 Mar 11 15:28 XXXX-1.0.10-RC1.pom

**What you expected to happen**:

POM gets uploaded.

**How to reproduce it (as minimally and precisely as possible)**:

Backup a folder containing only a POM and md5/sha files
try to re-upload them.

**Anything else we need to know?**:

**Environment**:
- nexus version: 3.29
- n3dr version (use `n3dr -v`):  nd3r version refs/tags/6.0.2
- OS (e.g: `cat /etc/os-release`): any
- Kernel (e.g. `uname -a`): any
- Others:

**Comment by kubealex** [comment]
@030  I found out the culprit :) 

The regexp that you are using  in github.com/030/n3dr/internal/artifacts.artifactTypeDetector() doesn't like the literals in the version suffix (in my case -RC[N]).

It also happen with a jar, so it's not a functional issue, it just needs to be able to recognize anything else than lower-case-literals.

Opened #203  for it!

**Comment by 030** [comment]
@kubealex Thank you for creating a PR. It looks like that GH-194 is related. I think that both PRs could be combined. Once the continue-on-error is implemented, your regex update could be merged as well.

**Comment by kubealex** [comment]
Great, I am actually reviewing it, To allow the version present in the artifact name to be different from the one reported in the 'folder' of the path.

IE: ./org/apache/whatever/0.1/org.apache.whatever-0.1.redhat-RC1

**Comment by 030** [comment]
@kubealex could you try whether n3dr 6.0.6 helps debugging this issue https://github.com/030/n3dr#skiperrors

**Comment by 030** [comment]
@kubealex https://github.com/030/n3dr#skiperrors Could you check whether it helps to overwrite the regex? Perhaps the default regex has to be changed.

**Comment by kubealex** [comment]
it surely helps, but at the moment the most complete regexp I've been able to generate ad use (I successfully backed up and migrated 3 nexus with more than 50gb each of artifacts) is the one in the MR.

**Comment by 030** [comment]
6.0.10
