### ISSUE TITLE
Doesn't work when nexus server address is IP

### ISSUE THREAD

**Issue by Just4test** [030/n3dr#205]
**What happened**:
When nexus host is IP, such like "127.0.0.1", n3dr doesn't work.

> ./n3dr backup -u admin -n http://127.0.0.1:8081  -r maven-releases
> FATA[0000]/Users/runner/work/n3dr/n3dr/cmd/n3dr/backup.go:32 main.glob..func1() The Nexus3 URL seems to be incorrect. Ensure that it does not end with a '/'. Error: 'URL: regular expression mismatch'

**What you expected to happen**:
It can work with IP.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- nexus version:
- n3dr version (use `n3dr -v`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by 030** [comment]
@Just4test Could you try whether version 6.0.7 solves the issue?
