### ISSUE TITLE
Upload downloaded repository under Windows fails (probably because of os specific path delimeter)

### ISSUE THREAD

**Issue by TheMaddinFromTqg** [030/n3dr#208]
**What happened**:
I exported / backed up a Nexus3 repository with n3dr to my local disc (folder E:\temp_repos\test) and want to upload it to another Nexus3 repository with this command line:
`n3dr upload --n3drRepo "E:\temp_repos\test" -n <theUrl> -u <theUser> -p <thePassword>`

I got this error:

`time="2021-04-14T18:09:34+02:00" level=fatal msg="check whether regexVersion: '(([a-z\\d\\-]+)|(([a-z\\d\\.]+)))' and regexClassifier: '(-(.*?(\\-([\\w.]+))?)?)?' match the artifact: 'E:\\temp_repos\\test\\com\\oracle\\ojdbc7\\12.1.0.1\\ojdbc7-12.1.0.1.jar'" func=main.glob..func3 file="D:/a/n3dr/n3dr/cmd/n3dr/upload.go:23"`

After watching into the code I thing the regex in upload.go must be OS dependent. Currently it is this concatinated string (upload.go line 84):

`^.*\/([\w\-\.]+)\/(([a-z\d\-]+)|(([a-z\d\.]+)))(-(.*?(\-([\w.]+))?)?)?\.([a-z]+)$`

Which match a path with forward slashes like 

`E:/temp_repos/test/com/oracle/ojdbc7/12.1.0.1./ojdbc7-12.1.0.1.jar`

But it do not match the path from the error message:

`E:\\temp_repos\\test\\com\\oracle\\ojdbc7\\12.1.0.1\\ojdbc7-12.1.0.1.jar`

**What you expected to happen**:
The content from the filesystem is uploaded to the Nexus maven repository. 

**How to reproduce it (as minimally and precisely as possible)**:
- Do the following on Windows
- Create a minimal file system repository (fake the export):
- Create folder structure E:\temp_repos\test\com\oracle\ojdbc7\12.1.0.1
- Place these two dummy files in it:
- ojdbc7-12.1.0.1.jar
- ojdbc7-12.1.0.1.pom
- Start upload to Nexus Repository with `n3dr upload --n3drRepo "E:\temp_repos\test" -n <theUrl> -u <theUser> -p <thePassword>`

**Anything else we need to know?**:
I think this problem depends to Window (because of using '\' instead of '/').

**Environment**:
- nexus version: 3.30.0-01
- n3dr version (use `n3dr -v`): 6.0.10
- OS (e.g: `cat /etc/os-release`): Windows Server 2019
- Kernel (e.g. `uname -a`): n/a
- Others: n/a

**Comment by 030** [comment]
@TheMaddinFromTqg  Could you try to upload by changing the regex using `N3DR_MAVEN_UPLOAD_REGEX_VERSION="some-regex" ./n3dr`?

**Comment by TheMaddinFromTqg** [comment]
@030 Thanks for your suggestion, but unfortunately this did not work. The N3DR_MAVEN_UPLOAD_REGEX_VERSION is for detecting the version part and not for detecting the path.

Here is the coresponding code snipped from the 6.0.10 version:

![grafik](https://user-images.githubusercontent.com/82529827/116543904-bd819100-a8ee-11eb-84b6-af2c28199f80.png)

As you can see the regex for the path is not editible via environment variable but exactly this is necessary here. I think the hardcoded part must be changed from the linux only version `^.*\/([\w\-\.]+)\/` to a linux and window version like this: `^.*(\/|\\\\)([\w\-\.]+)(\/|\\\\)`.

**Comment by 030** [comment]
6.0.13
