### ISSUE TITLE
performance/incremental backup

### ISSUE THREAD

**Issue by daudo** [030/n3dr#215]
Maybe I am doing something wrong, but backing up two small m2 repositories from localhost to a local directory seems to be very slow. In my case, it takes more than two minutes:

```
$ time n3dr backup --anonymous -n http://localhost:8081 -r repo1,repo2 --directory-prefix /home/nexus/n3dr-backup/maven.example.com/
[...]
real	2m6.210s
user	0m0.722s
sys	0m1.152s
```
the two repositories are only for testing and are extremely small with only a very small number of m2 artifacts:

```
$ du -h --max-depth=1 maven.example.com
1.2M	maven.example.com/repo1
6.8M	maven.example.com/repo2
8.0M	maven.example.com
```

There is almost zero load at the server, so that can't be a bottleneck.

As a "workaround" it would be very helpful if the backups could be done incrementally, so that only the diff is getting backed up. But I have no clue if you can do this using the nexus API.

**Comment by 030** [comment]
@daudo Could you check whether the [repositoriesV2 backup](https://github.com/030/n3dr#backup) option in 6.2.0 improves the download speeds of subsequent backups?
