### ISSUE TITLE
Windows, cannot upload to Nexus

### ISSUE THREAD

**Issue by fekal0id** [030/n3dr#223]
**What happened**:

I try use Windows machine to upload backup to new Nexus server

When i tried upload repository, get error - "CreateFile pbo_ceps: The system cannot find the file specified." func=main.glob..func3 file="D:/a/n3dr/n3dr/cmd/n3de/upload.go:23" 

Current folder - G:\nexus-dump
Content of folder - just one directory with backup of another Nexus server: pbo_ceps

Also pbo_ceps is name of Maven repository

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- nexus version: OSS 3.29.2-02
- n3dr version (use `n3dr -v`): 6.0.13
- OS (e.g: `cat /etc/os-release`): Windows 10
- Kernel (e.g. `uname -a`):
- Others:

**Comment by 030** [comment]
@fekal0id Did the upload work or did you experience other issues?
