### ISSUE TITLE
Npm upload doesn’t handle folders

### ISSUE THREAD

**Issue by prog99** [030/n3dr#231]
**What happened**:
When I do an upload to an npm repo from a folder with nested folders it gets a fatal error that folder name is a directory.

**What you expected to happen**:
It should handle folders. It managed to backup a repo with them preserving the structure.

**How to reproduce it (as minimally and precisely as possible)**:
Create a nested folder structure and attempt to upload

**Anything else we need to know?**:
n3dr handles downloading a repo with nested folders just fine and recreates this successfully

**Environment**:
- nexus version: 3.30.1-01
- n3dr version (use `n3dr -v`): built from source today
- OS (e.g: `cat /etc/os-release`): macOS catalina
- Kernel (e.g. `uname -a`):
- Others:

**Comment by 030** [comment]
Did you use the `repositories` or `repositoriesV2` command?

**Comment by lbg-mike-watson** [comment]
Neither.
n3dr upload -n MYHOST -t npm -r miketest -u admin -s
If I try repositoriesV2 then it throws an error
repositoriesV2.go:48 main.glob..func6() open : no such file or directory

**Comment by lbg-mike-watson** [comment]
Ah right, I think the documentation needs to be clearer. repositoriesV2 does work.
n3dr repositoriesV2 --upload -n HOSTNAME  -u admin -d --directory-prefix /somedirecotry
where HOSTNAME cannot have https:// in front of it and you need to specify the directory prefix.

**Comment by prog99** [comment]
Documentation confusion, works as per developers suggestion

**Comment by deegupt4** [comment]
I am facing the same issue , i have tried with both repositories and repoistoriesv2. 
how can i fix this?

**Comment by 030** [comment]
@deegupt4 Could you indicate what command was run? Did you specify `-r` and did you run the command from the root, e.g. if repo resides in /tmp/some-repo and the n3dr command should be run from /tmp or the directory-prefix command should be used.
