### ISSUE TITLE
Config file not working as expected

### ISSUE THREAD

**Issue by der-eismann** [030/n3dr#236]
**What happened**: I created a config file, but neither the snap nor a self-built binary seems to read the values

**What you expected to happen**: Using values from the config

**How to reproduce it (as minimally and precisely as possible)**:
```shell
$ cat ~/.n3dr/config.yml
n3drUser: n3dr
n3drPass: password
n3drURL: https://maven.example.com
$ n3dr repositoriesV2
INFO[0000]/home/sysop/projects/n3dr/cmd/n3dr/root.go:69 main.n3drHiddenHome() n3drHomeDir: '/home/sysop/.n3dr'             
INFO[0000]/home/sysop/projects/n3dr/cmd/n3dr/root.go:140 main.parseConfig() Using config file: '/home/sysop/.n3dr/config.yml' 
INFO[0000]/home/sysop/projects/n3dr/cmd/n3dr/root.go:122 main.parseVarsFromConfig() n3drUser empty. Reading if from '/home/sysop/.n3dr/config.yml' 
INFO[0000]/home/sysop/projects/n3dr/cmd/n3dr/root.go:127 main.parseVarsFromConfig() n3drPass empty. Reading if from '/home/sysop/.n3dr/config.yml' 
INFO[0000]/home/sysop/projects/n3dr/cmd/n3dr/root.go:133 main.parseVarsFromConfig() n3drURL empty. Reading if from '/home/sysop/.n3dr/config.yml'
```

**Anything else we need to know?**:
This doesn't look like a permission issue, I guess the Viper & Cobra integration isn't working correctly.

**Environment**:
- n3dr version (use `n3dr -v`): master
- OS (e.g: `cat /etc/os-release`): Fedora 35
- Kernel (e.g. `uname -a`): 5.15.12-200.fc35.x86_64

**Comment by 030** [comment]
@der-eismann Could you try 6.4.2?

**Comment by der-eismann** [comment]
Better, thanks!
