### ISSUE TITLE
socket: too many open files

### ISSUE THREAD

**Issue by xinity** [030/n3dr#257]
**What happened**: using n3dr to backup my nexus repositories using the latest version i have that kind of error:
```
ERRO[0165]/Users/runner/work/n3dr/n3dr/internal/artifacts/common.go:159 github.com/030/n3dr/internal/artifacts.(*RetryLogAdaptor).Printf() GET http://192.168.157.152:8081/repository/maven-central/org/apache/maven/scm/maven-scm-provider-accurev/1.9.4/maven-scm-provider-accurev-1.9.4.pom request failed: Get "http://192.168.157.152:8081/repository/maven-central/org/apache/maven/scm/maven-scm-provider-accurev/1.9.4/maven-scm-provider-accurev-1.9.4.pom": dial tcp 192.168.157.152:8081: socket: too many open files
```

**What you expected to happen**:
i expect to be able to backup the full maven-central repository without issues

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
i've followed the official KB which should fix this but no luck.

The nexus is hosted on Centos6 system
**Environment**:
- nexus version: 3.40.1
- n3dr version (use `n3dr -v`): 6.7.0
- OS (e.g: `cat /etc/os-release`): macos 12.4
- Kernel (e.g. `uname -a`):
- Others:

**Comment by 030** [comment]
@xinity Could you try the [repositoriesV2](https://github.com/030/n3dr#backup) command?

**Comment by xinity** [comment]
hey @030 i've tried this command:
` ./n3dr-macos-10.15 repositoriesV2 --backup -n 192.168.157.152:8081 --https=false -u admin -p '[admin password]' `

and here is the output :( 
``` 
open maven-local/org/servicestalend/job/AlimSsCatStatOrc/0.7.4/AlimSsCatStatOrc-0.7.4.pom: too many open files

goroutine 2427 [running]:
github.com/030/n3dr/internal/artifactsv2.(*Nexus3).downloadIfChecksumMismatchLocalFile.func1(0xc0011a2240)
	/Users/runner/work/n3dr/n3dr/internal/artifactsv2/download.go:136 +0x2ac
created by github.com/030/n3dr/internal/artifactsv2.(*Nexus3).downloadIfChecksumMismatchLocalFile
	/Users/runner/work/n3dr/n3dr/internal/artifactsv2/download.go:118 +0x2b8
panic: open maven-local/org/servicestalend/job/AlimNivDipl/0.7.3/AlimNivDipl-0.7.3.jar: too many open files

goroutine 2388 [running]:
github.com/030/n3dr/internal/artifactsv2.(*Nexus3).downloadIfChecksumMismatchLocalFile.func1(0xc0016fe480)
	/Users/runner/work/n3dr/n3dr/internal/artifactsv2/download.go:136 +0x2ac
created by github.com/030/n3dr/internal/artifactsv2.(*Nexus3).downloadIfChecksumMi
```

any hints ?

**Comment by 030** [comment]
@xinity Could you indicate how many files reside in your Nexus repository?

**Comment by xinity** [comment]
@030 please see the content of my nexus 
![Screenshot 2022-07-20 at 09 30 43](https://user-images.githubusercontent.com/1799009/179923558-56645f05-e495-4c4a-a747-837e873299bc.png)

let me know

**Comment by 030** [comment]
Could you check the max open file system setting on your system?

**Comment by xinity** [comment]
@030 `ulimit -f` says `unlimited` for the user that runs the nexus repository

**Comment by 030** [comment]
@xinity Could you try 6.7.2?

6.7.1:

```
~/Downloads/n3dr-ubuntu-20.04-671 repositoriesV2 --backup --directory-prefix /tmp/some-dir-22-aug-8a
```
results in:

```
++++++++++++++**********panic: open /tmp/some-dir-22-aug-8a/3rdparty-maven/org/apache/lucene/lucene-sandbox/8.5.0/lucene-sandbox-8.5.0.jar: too many open files
```

If 6.7.2 is used:

```
~/Downloads/n3dr-ubuntu-20.04-672 repositoriesV2 --backup --directory-prefix /tmp/some-dir-22-aug-8
```

then the download completes:

```
1,3G	/tmp/some-dir-22-aug-8

find /tmp/some-dir-22-aug-8 -type f | wc -l
8757
```
