### ISSUE TITLE
"lstat demo: no such file or directory" error in upload maven2 repo

### ISSUE THREAD

**Issue by LeBakii** [030/n3dr#260]
**What happened**: 
Error while uploading maven2 repo to nexus3 

INFO[0000] n3drHomeDir: '/root/snap/n3dr/75/.n3dr'      
INFO[0000] Using config file: '/root/snap/n3dr/75/.n3dr/config.yml' 
INFO[0000] n3drPass parameter empty. Reading it from config file: '/root/snap/n3dr/75/.n3dr/config.yml' 
INFO[0000] false                                        
INFO[0000]/home/runner/work/n3dr/n3dr/internal/artifacts/upload.go:364 github.com/030/n3dr/internal/artifacts.Nexus3.Upload() Uploading 'maven2'                           
FATA[0000]/home/runner/work/n3dr/n3dr/cmd/n3dr/upload.go:23 main.glob..func9() lstat thirdparty: no such file or directory

**Environment**:
- nexus version:
- n3dr version (use `n3dr -v`): 6.7.1
- OS (e.g: `cat /etc/os-release`):Ubuntu 22.04 LTS

**Comment by LeBakii** [comment]
The command is

n3dr upload -u user -n url -r thirparty

repo exist in  nexus.

**Comment by LeBakii** [comment]
Hi,

The repositoryV2 command for upload not working as well.

![Ekran Alıntısı](https://user-images.githubusercontent.com/110523873/183633718-ef3ef3aa-1066-4665-b32a-8cdf6e48a2cf.PNG)

**Comment by 030** [comment]
Could you try to upload it from your home folder?

https://github.com/030/n3dr#upload

> Note: if the snap package is used to upload artifacts, one has to ensure that the folder resides in the /home/$USER folder. Otherwise a: lstat <repository-name>: no such file or directory issue could occur.

**Comment by LeBakii** [comment]
Hi,

Thank u for response. I tried it worked but there is another problem. Couldn't fix it.
![Ekran Alıntısı](https://user-images.githubusercontent.com/110523873/183647643-9ebe154b-9ed7-4fbe-934f-93ebe8e37c28.PNG)

**Comment by LeBakii** [comment]
Hi,

Finally figure it out. It cannot get repository names because of https. I uploaded with https false with nexus ip and port.
