### ISSUE TITLE
N3DR backup aborts at empty directory with FATAL "does not seem to contain a Maven artifact"

### ISSUE THREAD

**Issue by dokaspar** [030/n3dr#278]
**What happened**:
I tested backing up a proxy repository as follows:
`n3dr backup -u admin -p pass -n https://my-nexus -r maven-release-proxy --skipErrors --logLevel debug`

After running a few minutes and downloading 356M of data, it stopped with this message:
`FATA[2022-11-02T08:50:52+01:00]/home/runner/work/n3dr/n3dr/cmd/n3dr/backup.go:42 main.glob..func1() URL: 'https://my-nexus/repository/maven-release-proxy/com' does not seem to contain a Maven artifact`

**What you expected to happen**:
The problem seems to be an empty root directory `com` which doesn't contain any Maven metadata.
I would expect at least the `--skipErrors` flag to work and skip over this artifact.

**How to reproduce it (as minimally and precisely as possible)**:
Backup a Maven repository that contains and empty `com` directory without any metadata.

**Environment**:
- Nexus version: OSS 3.38.1-01
- n3dr version (use `n3dr --version`): refs/tags/6.8.0
- OS (e.g: `cat /etc/os-release`): Red Hat Enterprise Linux release 8.6 (Ootpa)
- Kernel (e.g. `uname -a`): Linux 4.18.0-372.19.1.el8_6.x86_64

**Comment by 030** [comment]
Could you try to use the repositoriesV2 command?

https://github.com/030/n3dr/blob/main/examples/repositoriesV2/BACKUP.md

**Comment by dokaspar** [comment]
As far as I can tell, the repositoriesV2 doesn't let me backup a single repository, but only **all** of them. The repository I want to backup is only about 2G large... I have others that are terabytes in size, is there a way to ignore them all?

**Comment by 030** [comment]
@dokaspar Could you try to backup a single repository by using N3DR version 6.8.1?

n3dr repositoriesV2 --backup --n3drRepo some-repo --directory-prefix /tmp/some-dir

**Comment by dokaspar** [comment]
Thanks, the `n3dr repositoriesV2 --backup` command works. It took a bit of tweaking, but in the end, this was successful:
```
n3dr repositoriesV2 --backup -u admin -p *** -n example.com --basePathPrefix myproject/nexus --n3drRepo public-releases --directory-prefix /tmp/public-releases
```
