### ISSUE TITLE
[BUG]: Index out of range when downloading

### ISSUE THREAD

**Issue by krashekspres** [030/n3dr#35]
Tried to download entire repo, got index out of range:
```
panic: runtime error: index out of range

goroutine 1 [running]:
n3dr/cli.Nexus3.artifactName(0x7ffe55ce7f37, 0x24, 0x7ffe55ce7f66, 0x5, 0x7ffe55ce7f04, 0xa, 0x7ffe55ce7f19, 0x14, 0xc0004081e0, 0x52, ...)
	/go/n3dr/cli/cli.go:132 +0x329
n3dr/cli.Nexus3.downloadArtifact(0x7ffe55ce7f37, 0x24, 0x7ffe55ce7f66, 0x5, 0x7ffe55ce7f04, 0xa, 0x7ffe55ce7f19, 0x14, 0xc0004081e0, 0x52, ...)
	/go/n3dr/cli/cli.go:140 +0x8f
n3dr/cli.Nexus3.StoreArtifactsOnDisk(0x7ffe55ce7f37, 0x24, 0x7ffe55ce7f66, 0x5, 0x7ffe55ce7f04, 0xa, 0x7ffe55ce7f19, 0x14, 0xc0000000d4, 0xc0001ec000)
	/go/n3dr/cli/cli.go:196 +0x13a
main.main()
	/go/n3dr/main.go:26 +0x551

```

**Comment by 030** [comment]
Thanks for reporting. What command did you run? Did you use the docker?

**Comment by krashekspres** [comment]
`docker run -it --rm -v $PWD:/download nexus-cli:latest {credentials...} download`
I had to rebuild because I have old nexus with `/beta/` instead of `/v1/`, only change I did was in `cli/cli.go:LN22`.
It looks like it downloaded everything though.
Thank you for the tool btw :)

**Comment by 030** [comment]
@krashekspres Thank you for the feedback. The beta supported will be added.

**Comment by 030** [comment]
Index out of range issue fixed in https://github.com/030/n3dr/releases/tag/1.0.2

**Comment by 030** [comment]
Beta support will be added as well

**Comment by 030** [comment]
NEXUS_API_VERSION option added. It is now possible to consult `beta` and `v1` API.
