### ISSUE TITLE
Helm chart for automatic backups in k8s

### ISSUE THREAD

**Issue by EugenMayer** [030/n3dr#356]
Thank you for this awesome tool! We have written a couple of tools ourself ot deal with gems, composer and others when migrating nexus. Anyway, just thank you!

Are there yet any consideration running `n3dr` in a kubernetes environment using cron tasks (or as daemon) to automatically backup or sync a nexus?

I would consider creating such a helm chart, but this would require a bit of support and general interest here, maybe some smaller adoptions in exit code handling or similar.

What are your thoughts?

**Comment by 030** [comment]
Good idea. Yes a [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) could be created. Could you create a pull request?

**Comment by EugenMayer** [comment]
This will not go into this repo, this would not make sense and is unusual - helmchart go into a separate helm repo.

If i do one, it will first go to https://github.com/EugenMayer/helm-charts but for sure, after things settled, it might be somewhere on your side. I just do not like to get PM blocked early, this spoils the fun.

Still before i opt in, things need to be actually working system wise for me, so i can justify running this regularly. #357 is an absolute showstopper for me right now - pitty though. I really like your tooling!
