### ISSUE TITLE
Restore only works for npm

### ISSUE THREAD

**Issue by EugenMayer** [030/n3dr#357]
i created a full backup of the maven/npm/gem/raw repositories and then uploaded them to a entire fresh nexus.
I'am using the most recent n3dr (for linux) variant. Running the most recent nexus (3.47) on both, source and target servers.

For all the artifacts, only NPM seem to have worked flawlessly.

## Maven
- gradle version catalog artifacts (including a `.toml` file) have not been uploaded entirely, the toml file is missing. The toml file itself has been downloaded properly thogh
- maven artifacts that included `-sources.jar` have not been uploaded either (just the sources are missing)
- fat-jars, so `*-all.jar` have not been uploaded (but downloaded) 
- no `.obr` files have been uploaded - they have been downloaded though

## Gems
did not work at all. The download worked, i can just re-publish the gems using `gem nexus *` but the upload did not work at. Tried it several times, there is no error (it detects it is a gem repo but no gems are uploaded

```
INFO[0000]/home/runner/work/n3dr/n3dr/internal/app/n3dr/artifactsv2/upload/upload.go:63 github.com/030/n3dr/internal/app/n3dr/artifactsv2/upload.(*Nexus3).reposOnDisk() found the following localDiskRepos: '[gems]' 
INFO[0000]/home/runner/work/n3dr/n3dr/internal/app/n3dr/artifactsv2/upload/upload.go:340 github.com/030/n3dr/internal/app/n3dr/artifactsv2/upload.(*Nexus3).uploadArtifactsSingleDir() Uploading files to Nexus: 'nexus.kw.kontextwork.com' repository: 'gems'... 
INFO[0000]/home/runner/work/n3dr/n3dr/internal/app/n3dr/artifactsv2/upload/upload.go:82 github.com/030/n3dr/internal/app/n3dr/artifactsv2/upload.(*Nexus3).repoFormatLocalDiskRepo() format of repo: 'gems' is: 'rubygems'        
```

## Raw

Only partially downloaded (means not all files - files itself, if downloaded, seem to be correct), thus partially restored. So i assume the upload is working, but not the download.

----

Any way i can help making this a bit more robust in those areas?

**Comment by 030** [comment]
@EugenMayer Could you indicate how to reproduce the gem issue? How to download a gem using curl for example? Could you provide an example?

**Comment by EugenMayer** [comment]
@030 i would suggest splitting up those issue above in one for each type and keeping this issue as a parent track of the issues. For me right now, this project did more harm then good. Since no errors where thrown and it kind of looked good, i trusted the restore. Now i lost way to much assets ;/

If you like, i create an issue for each. To your question - the gems could be downloaded, so the download task seems to work. The upload does not work though.
