### ISSUE TITLE
When artifact path contains repository name, artifact directory on disk is incorrect

### ISSUE THREAD

**Issue by dbevacqua** [030/n3dr#75]
**What happened**:

When backing up an artifact whose path contains the repository name, artifact path on disk is incorrect.  For example if artifact URL is http://nexus.acme.com/repository/acme/com/acme/acme-tools/1.0.0/acme-tools-1.0.0.jar it will be downloaded to `acme-tools/acme-tools-1.0.0.jar`

**What you expected to happen**:

It should be downloaded to `com/acme/acme-tools/1.0.0/acme-tools-1.0.0.jar`

**How to reproduce it (as minimally and precisely as possible)**:

1. create a nexus repository called acme-tools
2. upload an artifact to com/acme/acme-tools/1.0.0/acme-tools-1.0.0.jar
3. back it up with `n3dr`
4. look at the path from the repository backup root to acme-tools-1.0.0.jar. it will have been truncated.

**Comment by 030** [comment]
Setting tag and testing functionally when new artifact has been created.

**Comment by 030** [comment]
@dbevacqua before releasing it, the CHANGELOG has to be updated. If you have time you could add another commit. If not possible I will do it this evening.

**Comment by 030** [comment]
3.1.1 seems to work fine. Another issue was found, but that already exists in 3.1.0 as well and is not related to the code change. @dbevacqua thanks again for creating a PR.
